# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='confirmation_token',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u041a\u043b\u044e\u0447 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u044f'),
        ),
    ]
