# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-18 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=2048, verbose_name='URI')),
                ('ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='ip \u0438\u0437 \u0437\u0430\u043f\u0440\u043e\u0441\u0430')),
                ('session_id', models.CharField(max_length=20, verbose_name='Id \u0441\u0435\u0441\u0441\u0438\u0438')),
                ('is_countable', models.BooleanField(default=False, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u043e\u0435 (\u0441\u0447\u0438\u0442\u0430\u0435\u0442\u0441\u044f \u0432 \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0435)')),
                ('log_time', models.DateTimeField(default=datetime.datetime(2019, 3, 18, 16, 19, 43, 556000), verbose_name='\u0412\u0440\u0435\u043c\u044f \u0444\u0438\u043a\u0441\u0430\u0446\u0438\u0438')),
                ('stat_time', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=2048, verbose_name='URI')),
                ('fl_id', models.BigIntegerField(verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0439 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043d\u044b\u0439 Id \u0434\u043b\u044f \u0434\u0430\u043d\u043d\u043e\u0433\u043e uri \u0438\u0437 \u043b\u043e\u0433\u0430')),
                ('stat_time', models.DateTimeField(default=datetime.datetime(2019, 3, 18, 16, 19, 43, 556000), verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0440\u0430\u0441\u0447\u0435\u0442\u0430')),
                ('cnt', models.BigIntegerField(verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u0421\u0447\u0435\u0442\u0447\u0438\u043a \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0439',
                'verbose_name_plural': '\u0421\u0447\u0435\u0442\u0447\u0438\u043a\u0438 \u043f\u043e\u0441\u0435\u0449\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together=set([('uri',)]),
        ),
    ]
