# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-19 11:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uristat', '0003_auto_20190319_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='fl_id',
        ),
        migrations.AlterField(
            model_name='followlog',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0444\u0438\u043a\u0441\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='stat_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0440\u0430\u0441\u0447\u0435\u0442\u0430'),
        ),
    ]
